<div class="panel-wrap panel-danger center-block panel-wrap post-add">
    <div class="panel-heading">
        <h3 class="panel-title">Add new advertisement<span class="panel-text-right">Or <a href="/home">return to
                    home</a></span></h3>
    </div>
    <div class="panel-body">

        <p class="text-danger">
            Fields marked with * are required!
        </p>

        <label for="dropzone">Add photo of your goods</label>

        <form id="dropzone" action="/imagedownload" class="dropzone"></form>

        <form action="/addpost" method="post">
            <div class="form-group">
                <label for="category"><span class="text-danger">*</span> Category</label>
                <select name="category" id="category" class="form-control">
                    <?php foreach ($data['categories'] as $v) : ?>
                        <option
                            value="<?= htmlspecialchars($v['id']) ?>"><?php echo htmlspecialchars($v['title']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="subject"><span class="text-danger">*</span> Subject</label>
                <input type="text" class="form-control" id="subject" placeholder="Enter subject" name="subject"
                       required>
            </div>
            <div class="form-group">
                <label for="price"><span class="text-danger">*</span> Price($)</label>
                <input type="number" step="any" class="form-control" id="price" placeholder="Tell us the price of your goods"
                       name="price" required>
            </div>
            <div class="form-group">
                <label for="description"><span class="text-danger">*</span> Description</label>
                    <textarea class="form-control" id="description" placeholder="Tell us about your goods" required
                              rows="5" name="description"></textarea>
            </div>


            <input type="submit" class="btn btn-danger pull-right" value="Create">
        </form>

    </div>

</div>

<script src="/application/assets/js/dropzone.min.js"></script>