<div class="panel-wrap panel-primary center-block panel-wrap">
    <div class="panel-heading">
        <h3 class="panel-title">Registration: step 3 <span class="panel-text-right"></h3>
    </div>
    <div class="panel-body">
        <h3>Congratulations!</h3>

        <p>You just confirmed your registration on <?php echo Config::get('site')['host'] ?></p>

        <p>Please, <a href="/login">login</a> and add details into your profile</p>
    </div>
</div>
