<div class="edit-profile">
    <div class="center-block width60p">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Edit profile <span class="panel-text-right">Or <a href="/profile">return to
                            viewing
                            profile</a></span></h3>
            </div>
            <div class="panel-body">

                <form action="/edit" method="post">
                    <div class="form-group">
                        <label for="login">Login</label>
                        <input type="text" class="form-control" id="login" name="login" placeholder="Enter login"
                               value="<?= htmlspecialchars($data['user']['login'])?>">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"
                               value="<?= htmlspecialchars($data['user']['email'])?>">
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="old-password">Old password</label>
                                <input type="password" class="form-control" id="old-password" name="old-password"
                                       placeholder="Password">
                            </div>
                            <div class="col-md-6">
                                <label for="new-password">New password</label>
                                <input type="password" class="form-control" id="new-password" name="new-password"
                                       placeholder="Password">
                            </div>
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label for="fname">First name</label>
                        <input type="text" class="form-control" id="fname" name="firstname" placeholder="Enter first name"
                               value="<?= htmlspecialchars($data['profile']['firstname'])?>">
                    </div>

                    <div class="form-group">
                        <label for="lname">Last name</label>
                        <input type="text" class="form-control" id="lname" name="lastname" placeholder="Enter last name"
                               value="<?= htmlspecialchars($data['profile']['lastname']); ?>">
                    </div>

                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="tel" class="form-control" id="phone" name="phone" placeholder="Enter phone number"
                               value="<?= htmlspecialchars($data['profile']['phone'])?>">
                    </div>

                    <div class="form-group">
                        <label for="skype">Skype</label>
                        <input type="text" class="form-control" id="skype" name="skype" placeholder="Enter skype nickname"
                               value="<?= htmlspecialchars($data['profile']['skype'])?>">
                    </div>

                    <input type="submit" class="btn btn-iris pull-right" value="Save">
                </form>
            </div>

        </div>
    </div>
</div>