<div class="edit-profile">
    <div class="panel-wrap panel-primary center-block panel-wrap">
        <div class="panel-heading">
            <h3 class="panel-title">Edit profile <span class="panel-text-right">Or <a href="/profile">return to
                        viewing
                        profile</a></span></h3>
        </div>
        <div class="panel-body">

            <?= $data['message']; ?>

                <form action="/edit" method="post">
                    <div class="form-group">
                        <label for="login">Login</label>
                        <?= $data['login']; ?>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <?= $data['email']; ?>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="old-password">Old password</label>
                                <?= $data['old-password']; ?>
                            </div>
                            <div class="col-md-6">
                                <label for="new-password">New password</label>
                                <?= $data['new-password']; ?>
                            </div>
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label for="fname">Full Name</label>
                        <?= $data['fullName']; ?>
                    </div>

                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <?= $data['phone']; ?>
                    </div>

                    <div class="form-group">
                        <label for="skype">Skype</label>
                        <?= $data['skype']; ?>
                    </div>

                    <div class="form-group">
                        <label for="birthday">Birthday</label>
                        <?= $data['birthday']; ?>
                    </div>

                <input type="submit" class="btn btn-iris pull-right" value="Save">
            </form>
        </div>

    </div>
</div>