<div class="margin-rl7">

    <div class="col-md-3">
        <img src="/application/assets/img/ads-logo.svg" alt="Logo" class="logo"/>
    </div>
    <div class="col-md-9">
        <div class="hello">
            <div><h1>Sell smarter,<br/>not harder</h1></div>
            <div><h1>Just sell it!</h1></div>
            <div><h1>Sell different</h1></div>
            <div><h1>Sells like a dream</h1></div>
            <div><h1>Pss..., need some advertisements?</h1></div>
            <div><h1>Sell 'em all!</h1></div>
            <div><h1>The king of selling</h1></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <h3>Recent posts</h3>
</div>

<ul class="grid effect-1" id="grid">
    <?php foreach ($data['resentAds'] as $v) : ?>
        <?php ChromePhp::log($v); ?>
        <!--Element start-->
        <li>
            <div class="item">
                <?php if (!empty($v['images'])) : ?>
                    <a href="<?= htmlspecialchars($v['images'][0]['imageName']) ?>" data-lightbox="image-1"
                       data-title="My caption" id="<?= htmlspecialchars($v['images'][0]['id']) ?>">
                        <img src="<?= htmlspecialchars($v['imagesPreview'][0]['imageName']) ?>" alt="slider1"
                             class="thumbnail img-responsive"/>
                    </a>
                <?php endif; ?>

                <h1><?= $v['subject'] ?></h1>

                <div id="textbox">
                    <p class="pull-left"><?= $v['creationDate'] ?></p>

                    <p class="pull-right"><a href="/postdetail/<?= $v['id'] ?>">See more <span
                                class="glyphicon glyphicon-open"></span></a>
                    </p>
                </div>
            </div>
        </li>
        <!--Element end-->

    <?php endforeach; ?>

</ul>

<!-- Need for tiles start-->
<script src="/application/assets/js/modernizr.custom.js"></script>
<script src="/application/assets/js/masonry.pkgd.min.js"></script>
<script src="/application/assets/js/imagesloaded.js"></script>
<script src="/application/assets/js/classie.js"></script>
<script src="/application/assets/js/AnimOnScroll.js"></script>
<script src="/application/assets/js/lightbox.min.js"></script>
<script src="/application/assets/js/textCarousel.js"></script>
<script type="text/javascript" src="/application/assets/js/slick.min.js"></script>

<script>
    new AnimOnScroll(document.getElementById('grid'), {
        minDuration: 0.4,
        maxDuration: 0.7,
        viewportFactor: 0.2
    });
</script>
<!-- Need for tiles start-->