<div class="margin-rl7">

    <div class="col-md-3">
        <img src="/application/assets/img/ads-logo.svg" alt="Logo" class="logo"/>
    </div>
    <div class="col-md-9">
        <div class="hello">
            <h1>Some hello words</h1>

            <p>
                Definition, beauty, and voyage. Understanding at the homeworld was the voyage of
                adventure, deceived
                to a devastated hur'q. Tremble patiently like a sub-light processor. The kahless is more sonic
                shower now than machine. greatly exaggerated and nosily boldly.
            </p>
        </div>
    </div>

    <div class="clearfix"></div>

    <h3>Recent posts</h3>
</div>

<ul class="grid effect-1" id="grid">

    <!--Element start-->
    <li>
        <div class="item">
            <a href="/application/demoimg/1.jpg" data-lightbox="image-1" data-title="My caption">
                <img src="/application/demoimg/1.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <!--Element end-->

    <li>
        <div class="item">
            <a href="/application/demoimg/2.jpg" data-lightbox="image-2" data-title="My caption">
                <img src="/application/demoimg/2.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/3.jpg" data-lightbox="image-3" data-title="My caption">
                <img src="/application/demoimg/3.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/4.jpg" data-lightbox="image-4" data-title="My caption">
                <img src="/application/demoimg/4.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>

    <li>
        <div class="item">
            <a href="/application/demoimg/2.jpg" data-lightbox="image-5" data-title="My caption">
                <img src="/application/demoimg/2.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/3.jpg" data-lightbox="image-6" data-title="My caption">
                <img src="/application/demoimg/3.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/4.jpg" data-lightbox="image-7" data-title="My caption">
                <img src="/application/demoimg/4.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/2.jpg" data-lightbox="image-8" data-title="My caption">
                <img src="/application/demoimg/2.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/3.jpg" data-lightbox="image-9" data-title="My caption">
                <img src="/application/demoimg/3.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
    <li>
        <div class="item">
            <a href="/application/demoimg/4.jpg" data-lightbox="image-10" data-title="My caption">
                <img src="/application/demoimg/4.jpg" alt="slider1"/>
            </a>

            <h1>Header</h1>

            <div id="textbox">
                <p class="pull-left">2014-12-27</p>

                <p class="pull-right"><a href="#">See more <span class="glyphicon glyphicon-open"></span></a></p>
            </div>
        </div>
    </li>
</ul>

<!-- Need for tiles start-->
<script src="/application/assets/js/modernizr.custom.js"></script>
<script src="/application/assets/js/masonry.pkgd.min.js"></script>
<script src="/application/assets/js/imagesloaded.js"></script>
<script src="/application/assets/js/classie.js"></script>
<script src="/application/assets/js/AnimOnScroll.js"></script>
<script src="/application/assets/js/lightbox.min.js"></script>

<script>
    new AnimOnScroll(document.getElementById('grid'), {
        minDuration: 0.4,
        maxDuration: 0.7,
        viewportFactor: 0.2
    });
</script>
<!-- Need for tiles start-->