<div class="center-block width60p" id="login">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Login to your account <span class="panel-text-right">Or <a href="/home">return to
                        home</a></span></h3>
        </div>
        <div class="panel-body">

            <!-- Login form start -->
            <form action="/user/login" method="post">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password"
                           placeholder="Password">
                </div>

                <div class="checkbox">
                    <div class="icheckbox_flat">
                        <input id="remember" name="remember" type="checkbox">
                    </div>
                    <label for="remember"> Remember me</label>
                </div>
                <input type="submit" class="btn btn-success pull-right" value="Sign in">
            </form>
            <!-- Login form start -->

        </div>
        <div class="panel-footer">
            <a href="/restore">Forgot your password?</a>
        </div>
    </div>
</div>

<!-- Need for checkbox start -->
<script src="/application/assets/js/icheck.js"></script>
<script>
    $(document).ready(function () {
        $('.icheckbox_flat').iCheck({
            checkboxClass: 'icheckbox_flat'
        });
    });
</script>
<!-- Need for checkbox start -->