<div class="panel-wrap panel-success center-block panel-wrap" id="login">
    <div class="panel-heading">
        <h3 class="panel-title">Login to your account <span class="panel-text-right">Or <a href="/home">return to
                    home</a></span></h3>
    </div>
    <div class="panel-body">

        <?= $data['message']; ?>

        <!-- Login form start -->
        <form action="/login" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <?= $data['email']; ?>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <?= $data['password']; ?>
            </div>

            <div class="checkbox">
                <div class="icheckbox_flat">
                    <input id="remember" name="remember" type="checkbox">
                </div>
                <label for="remember"> Remember me</label>
            </div>
            <input type="submit" class="btn btn-success pull-right" value="Sign in">
        </form>
        <!-- Login form start -->

    </div>
    <div class="panel-footer">
        <a href="/restore">Forgot your password?</a>
    </div>
</div>

<!-- Need for checkbox start -->
<script src="/application/assets/js/icheck.js"></script>
<script>
    $(document).ready(function () {
        $('.icheckbox_flat').iCheck({
            checkboxClass: 'icheckbox_flat'
        });
    });
</script>
<!-- Need for checkbox start -->