<div class="center-block width60p" id="plan">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Choose your payment plan<span class="panel-text-right">Or <a href="/home">return to
                        home</a></span></h3>
        </div>
        <div class="panel-body">
            <form action="#" method="post">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password"
                           placeholder="Password">
                </div>
                <input type="submit" class="btn btn-success pull-right" value="Sign in">
            </form>
        </div>
    </div>
</div>