<div class="panel-wrap panel-success center-block panel-wrap" id="plan">
    <div class="panel-heading">
        <h3 class="panel-title">Subscribe 4 new plan NOW<span class="panel-text-right">Or <a href="/home">return to
                    home</a></span></h3>
    </div>
    <div class="panel-body">
        <table id="plans">
            <tr>
                <th>FREE</th>
                <th>PRO</th>
                <th>BUSINESS</th>
            </tr>
            <tr>
                <td>Just ONE advertisement available 4 u now</td>
                <td><a href="/user/paypal?type=pro"><img
                            src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"></a></td>
                <td><a href="/user/paypal?type=business"><img
                            src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"></a></td>
            </tr>
        </table>
    </div>
</div>