<?php
$planData = $this->_data;
?>
<div class="pricing text-center margin-t7p">
    <h2>Greetings, you now on <i><?php echo $planData['currentPlan']?></i> plan. You can change your subscribe by available buttons below.</h2>
    <ul>
        <li class="unit price-primary">
            <div class="price-title"><h3>$0</h3>

                <p>&emsp;</p>
            </div>
            <div class="price-body">
                <h4>FREE</h4>
                <ul>
                    <li>1 advertisement</li>
                </ul>
            </div>
            <div class="price-foot">
                <button type="button" class="btn btn-primary <?php echo $planData['disableFree'];?>">Try Now</button>
            </div>
        </li>
        <li class="unit price-success active">
            <div class="price-title"><h3>$199</h3>

                <p>per month</p></div>
            <div class="price-body"><h4>Business</h4>

                <ul>
                    <li>Unlimited advertisements</li>
                </ul>
            </div>
            <div class="price-foot">
                <a href="/user/paypal?type=business"><button type="button" class="btn btn-success <?php echo $planData['disableBusiness'];?>">Buy Now</button></a>
            </div>
        </li>
        <li class="unit price-warning">
            <div class="price-title"><h3>$99</h3>

                <p>per month</p></div>
            <div class="price-body"><h4>Pro</h4>

                <ul>
                    <li>1000 advertisements</li>
                </ul>
            </div>
            <div class="price-foot">
                <a href="/user/paypal?type=pro"><button type="button" class="btn btn-warning <?php echo $planData['disablePro'];?>">Buy Now</button></a>
            </div>
        </li>
    </ul>
</div>