<div class="row">
    <label for="categories">Categories</label>
    <select name="categories" id="categories" class="form-control">
        <?php foreach ($data['categories'] as $v) : ?>
            <option
                value="<?php echo htmlspecialchars($v['id']) ?>"><?php echo htmlspecialchars($v['title']) ?></option>
        <?php endforeach; ?>

    </select>
</div>

<div class="posts">

    <?php foreach ($data['advertisements'] as $v) : ?>

        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1><?php echo date("Y-m-d", $v['creationDate']) ?></h1>

                <h2><?php echo date("H:i", $v['creationDate']) ?></h2>
            </div>

            <div class="col-md-2">
                <a href="/application/demoimg/1.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/1.jpg" alt="slider1" class="thumbnail img-responsive"/>
                </a>

                <div class="hidden">
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
                </div>
            </div>

            <div class="col-md-6 text">
                <h1>
                    <a href="/postdetail/<?php echo htmlspecialchars($v['id']) ?>"><?php echo htmlspecialchars($v['subject']) ?></a>
                </h1>

                <a href="/profile"><?php echo htmlspecialchars($v['login']) ?></a>

            </div>
            <div class="col-md-2 text-right">
                <h1><?php echo htmlspecialchars($v['price']) ?>$</h1>
            </div>
        </div>

    <?php endforeach; ?>

</div>

<script src="/application/assets/js/lightbox.min.js"></script>