<div class="post-detail">
    <div class="row">
        <div class="col-md-12">
            <h3><?php echo htmlspecialchars($data['title']) ?></h3>

            <p><a href="/postlist" class="pull-left"><i class="glyphicon glyphicon-arrow-left"></i> Back to
                    list</a></p>

            <p class="pull-right"><?php echo htmlspecialchars($data['creationDate']) ?></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h4><?php echo htmlspecialchars($data['subject']) ?></h4>
        </div>
    </div>
    <div class="row body">
        <div class="col-md-8">

            <?php if(!empty($data['images'])) : ?>
            <div class="post-thumbnail thumbnail">
                <a href="<?= htmlspecialchars($data['images'][0]['imageName']) ?>" data-lightbox="image-1" data-title="My caption" id="<?= htmlspecialchars($data['images'][0]['id']) ?>">
                    <img src="<?= htmlspecialchars($data['images'][0]['imageName']) ?>" alt="slider1" class="img-responsive"/>
                </a>

                <div class="photo-amount"><?= htmlspecialchars(count($data['images'])) ?> photo</div>
            </div>

                <div class="hidden">
                    <?php for( $i = 1 ; $i < count($data['images']); $i++) : ?>
                        <a href="<?= htmlspecialchars($data['images'][$i]['imageName']) ?>" data-lightbox="image-1" data-title="My caption" id="<?= htmlspecialchars($data['images'][$i]['id']) ?>"></a>
                    <?php endfor; ?>
                </div>

            <?php endif; ?>



            <p class="description">
                <?php echo htmlspecialchars($data['description']) ?>
            </p>
        </div>
        <div class="col-md-4">
            <div class="price"><h3>$<?php echo htmlspecialchars($data['price']) ?></h3></div>
            <div class="author">
                <p>CONTACT THE AUTHOR OF THE ADVERTISEMENT</p>

                <h4><a href="/profile"><?php echo htmlspecialchars($data['login']) ?></a></h4>

                <a data-toggle="collapse" href="#contact-info" aria-expanded="false" aria-controls="contact-info">
                    Show detail
                </a>

                <div class="collapse" id="contact-info">
                    <div class="well">
                        <p><i class="glyphicon glyphicon-earphone"></i> 214-748-3647</p>

                        <p><i class="icon-skype"></i> dude_in_skype</p>

                        <p><i class="glyphicon glyphicon-map-marker"></i> <a
                                href="http://maps.google.com/?q=Amsterdam, De Wallen St. 1">Amsterdam, De Wallen St.
                                1</a></p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="/application/assets/js/lightbox.min.js"></script>