<div class="post-detail">
    <div class="row">
        <div class="col-md-12">
            <h3><?php echo htmlspecialchars($data['ads'][0]['subject']) ?></h3>

            <p><a href="/postlist" class="pull-left"><i class="glyphicon glyphicon-arrow-left"></i> Back to
                    list</a></p>

            <p class="pull-right"><?php echo htmlspecialchars($data['ads'][0]['creationDate']) ?></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h4>Fly wihtout life, and we won’t control a species. Ancient starlight travels lead to the collision
                course.</h4>
        </div>
    </div>
    <div class="row body">
        <div class="col-md-8">
            <div class="post-thumbnail thumbnail">
                <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/2.jpg" alt="slider1" class="img-responsive"/>
                </a>

                <div class="photo-amount">4 photo</div>
            </div>

            <div class="hidden">
                <a href="/application/demoimg/1.jpg" data-lightbox="image-1" data-title="My caption"></a>
                <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
            </div>

            <p class="description">
                <?php echo htmlspecialchars($data['ads'][0]['description']) ?>
            </p>
        </div>
        <div class="col-md-4">
            <div class="price"><h3><?php echo htmlspecialchars($data['ads'][0]['price']) ?>$</h3></div>
            <div class="author">
                <p>CONTACT THE AUTHOR OF THE ADVERTISEMENT</p>

                <h4><a href="/profile"><?php echo htmlspecialchars($data['ads'][0]['login']) ?></a></h4>

                <a data-toggle="collapse" href="#contact-info" aria-expanded="false" aria-controls="contact-info">
                    Show detail
                </a>

                <div class="collapse" id="contact-info">
                    <div class="well">
                        <p><i class="glyphicon glyphicon-earphone"></i> 214-748-3647</p>

                        <p><i class="icon-skype"></i> dude_in_skype</p>

                        <p><i class="glyphicon glyphicon-map-marker"></i> <a
                                href="http://maps.google.com/?q=Amsterdam, De Wallen St. 1">Amsterdam, De Wallen St.
                                1</a></p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="/application/assets/js/lightbox.min.js"></script>