<div class="row">
    <label for="categories">Categories</label>
    <select name="categories" id="categories" class="form-control">
        <option value="1">Automobiles</option>
        <option value="2">Furniture</option>
        <option value="3">Toys</option>
    </select>
</div>

<!-- Will be repeat in loop start -->
<div class="row post-list vertical-align">
    <div class="col-md-2 text-center">
        <h1>2015-01-05</h1>
        <h2>17:51:48</h2>
    </div>

    <div class="col-md-4 vertical-align">
        <div class="col-md-8 main-image">
            <a href="/application/demoimg/1.jpg" data-lightbox="image-1" data-title="My caption" class="thumbnail">
                <img src="/application/demoimg/preview/1.jpg" alt="slider1"/>
            </a>
        </div>
        <div class="col-md-4 relative-images">
            <ul class="image-preview">
                <li>
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"
                       class="thumbnail">
                        <img src="/application/demoimg/preview/2.jpg" alt="slider2"/>
                    </a>
                </li>
                <li>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"
                       class="thumbnail">
                        <img src="/application/demoimg/preview/3.jpg" alt="slider3"/>
                    </a>
                </li>
                <li>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"
                       class="thumbnail">
                        <img src="/application/demoimg/preview/4.jpg" alt="slider4"/>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-5 text">
        <h1>Post's subject <small><a href="">View detail</a></small></h1>

        <p>
            Calcarias peregrinatione in revalia! A falsis, competition fortis adiurator. Verpa, poeta, et abactor.
            The
            machine is more vogon now than alien. proud and pedantically mysterious. Harvest proudly like a bare
            sun.
            Ships are the sensors of the terrifying moon. Dozens of honors will be lost in minerals like starlight
            travels in sensors Why does the alien go? The paralysis is a devastated creature. View wihtout ionic
            cannon,
            and we won’t accelerate a starship. The reliable admiral wildly beams the starship. Never outweigh a
            crew.
            Modification, galaxy, and plasma.
        </p>
    </div>
    <div class="col-md-1 text-center">
        <h1>$500</h1>
    </div>
</div>
<!-- Will be repeat in loop end -->

<div class="row post-list vertical-align">
    <div class="col-md-2 text-center">
        <h1>2015-01-05</h1>
        <h2>15:21:12</h2>
    </div>
    <div class="col-md-4 vertical-align">
        <div class="col-md-8 main-image">
            <a href="/application/demoimg/1.jpg" data-lightbox="image-2" data-title="My caption" class="thumbnail">
                <img src="/application/demoimg/preview/1.jpg" alt="slider1"/>
            </a>
        </div>
        <div class="col-md-4 relative-images">
            <ul class="image-preview">
                <li>
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-2" data-title="My caption"
                       class="thumbnail">
                        <img src="/application/demoimg/preview/2.jpg" alt="slider2"/>
                    </a>
                </li>
                <li>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-2" data-title="My caption"
                       class="thumbnail">
                        <img src="/application/demoimg/preview/3.jpg" alt="slider3"/>
                    </a>
                </li>
            </ul>


        </div>
    </div>
    <div class="col-md-5 text">
        <h1>Post's subject <small><a href="">View detail</a></small></h1>

        <p class="description">
            Calcarias peregrinatione in revalia! A falsis, competition fortis adiurator. Verpa, poeta, et abactor.
            The
            machine is more vogon now than alien. proud and pedantically mysterious. Harvest proudly like a bare
            sun.
            Ships are the sensors of the terrifying moon. Dozens of honors will be lost in minerals like starlight
            travels in sensors Why does the alien go? The paralysis is a devastated creature. View wihtout ionic
            cannon,
            and we won’t accelerate a starship. The reliable admiral wildly beams the starship. Never outweigh a
            crew.
            Modification, galaxy, and plasma.
        </p>
    </div>
    <div class="col-md-1 text-center">
        <h1>$50000</h1>
    </div>
</div>


<script src="/application/assets/js/lightbox.min.js"></script>