<div class="profile">
    <div class="row">
        <?php
        $saveChanges = $_SESSION['saveChanges'];
        if ($saveChanges){
            unset ($_SESSION['saveChanges']);
            echo '<h4 class="text-success"><ins>Save changes</ins></h4>';
        }
        ?>
        <h3>
            <?php
            echo htmlspecialchars($data['login']).' ';
            if ($_SESSION['userId'] == $data['userId']) {
                echo '<small><a href="/edit">[edit]</a></small>';
            } else {
                echo '<small><a href="">[complain]</a></small>';
            }
            ?>
        </h3>
        <div class="well">
            <p><i class="glyphicon glyphicon-user"></i> <?= htmlspecialchars($data['fullName']).' '.htmlspecialchars($data['lastname'])?></p>

            <p><i class="glyphicon glyphicon-earphone"></i> <?= htmlspecialchars($data['phone'])?></p>

            <p><i class="icon-skype"></i> <?= htmlspecialchars($data['skype'])?></p>

            <p><i class="glyphicon glyphicon-map-marker"></i> <?= htmlspecialchars($data['birthday'])?></p>
        </div>
    </div>
    <div class="row">
        <h3>some_dude_login's posts</h3>
    </div>

    <!-- Will be repeat in loop start -->
    <div class="posts">
        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1>2015-01-05</h1>

                <h2>17:51:48</h2>
            </div>

            <div class="col-md-2">
                <a href="/application/demoimg/1.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/1.jpg" alt="slider1" class="thumbnail img-responsive"/>
                </a>

                <div class="hidden">
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
                </div>
            </div>

            <div class="col-md-6 text">
                <h2><a href="/postlist">Category</a></h2>

                <h1><a href="/postdetail">Post subject</a></h1>

                <p>Holland, Amsterdam</p>

            </div>
            <div class="col-md-2 text-right">
                <h1>$500</h1>
            </div>
        </div>
        <!-- Will be repeat in loop end -->

        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1>2015-01-05</h1>

                <h2>17:51:48</h2>
            </div>

            <div class="col-md-2">
                <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/2.jpg" alt="slider1" class="thumbnail img-responsive"/>
                </a>

                <div class="hidden">
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
                </div>
            </div>

            <div class="col-md-6 text">
                <h2><a href="/postlist">Category</a></h2>

                <h1><a href="/postdetail">Post subject</a></h1>

                <p>Holland, Amsterdam</p>

            </div>
            <div class="col-md-2 text-right">
                <h1>$500</h1>
            </div>
        </div>
        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1>2015-01-05</h1>

                <h2>17:51:48</h2>
            </div>

            <div class="col-md-2">
                <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/3.jpg" alt="slider1" class="thumbnail img-responsive"/>
                </a>

                <div class="hidden">
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
                </div>
            </div>

            <div class="col-md-6 text">
                <h2><a href="/postlist">Category</a></h2>

                <h1><a href="/postdetail">Post subject</a></h1>

                <p>Holland, Amsterdam</p>

            </div>
            <div class="col-md-2 text-right">
                <h1>$500</h1>
            </div>
        </div>
        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1>2015-01-05</h1>

                <h2>17:51:48</h2>
            </div>

            <div class="col-md-2">
                <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption">
                    <img src="/application/demoimg/preview/4.jpg" alt="slider1" class="thumbnail img-responsive"/>
                </a>

                <div class="hidden">
                    <a href="/application/demoimg/2.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/3.jpg" data-lightbox="image-1" data-title="My caption"></a>
                    <a href="/application/demoimg/4.jpg" data-lightbox="image-1" data-title="My caption"></a>
                </div>
            </div>

            <div class="col-md-6 text">
                <h2><a href="/postlist">Category</a></h2>

                <h1><a href="/postdetail">Post subject</a></h1>

                <p>Holland, Amsterdam</p>

            </div>
            <div class="col-md-2 text-right">
                <h1>$500</h1>
            </div>
        </div>
    </div>
</div>

<script src="/application/assets/js/lightbox.min.js"></script>
