<div class="profile">
    <div class="row">
        <?php
        $changesSaved = $_SESSION['$changesSaved'];
        if ($changesSaved){
            unset ($_SESSION['$changesSaved']);
            echo '<h4 class="text-success"><ins>Changes saved</ins></h4>';
        }
        ?>
        <h3>
            <?php
            echo htmlspecialchars($data['login']).' ';
            if ($_SESSION['userId'] == $data['userId']) {
                echo '<small><a href="/edit">[edit]</a></small>';
            } else {
                echo '<small><a href="">[complain]</a></small>';
            }
            ?>
        </h3>
        <div class="well">
            <p><i class="glyphicon glyphicon-user"></i> <?= htmlspecialchars($data['fullName']).' '.htmlspecialchars($data['lastname'])?></p>

            <p><i class="glyphicon glyphicon-earphone"></i> <?= htmlspecialchars($data['phone'])?></p>

            <p><i class="icon-skype"></i> <?= htmlspecialchars($data['skype'])?></p>

            <p><i class="glyphicon glyphicon-calendar"></i> <?= htmlspecialchars($data['birthday'])?></p>
        </div>
    </div>
    <div class="row">
        <h3>Posts</h3>
    </div>

    <?php foreach ($data['advertisements'] as $v) : ?>

        <div class="row post-list vertical-align">
            <div class="col-md-2 text-right">
                <h1><?php echo date("Y-m-d", $v['creationDate']) ?></h1>

                <h2><?php echo date("H:i", $v['creationDate']) ?></h2>
            </div>

            <div class="col-md-2">

                <?php if(!empty($v['images'])) : ?>

                    <a href="<?= htmlspecialchars($v['images'][0]['imageName']) ?>" data-lightbox="image-<?php echo htmlspecialchars($v['id']) ?>" data-title="<?php echo htmlspecialchars($v['subject']) ?>" id="<?= htmlspecialchars($v['images'][0]['id']) ?>">
                        <img src="<?= htmlspecialchars($v['imagesPreview'][0]['imageName']) ?>" alt="img<?php echo htmlspecialchars($v['id']) ?>" class="thumbnail img-responsive" />
                    </a>

                    <div class="hidden">

                        <?php for ( $i = 1 ; $i < count($v['images']); $i++) : ?>
                            <a href="<?= htmlspecialchars($v['images'][$i]['imageName']) ?>" data-lightbox="image-<?php echo htmlspecialchars($v['id']) ?>" data-title="<?php echo htmlspecialchars($v['subject']) ?>" id="<?= htmlspecialchars($v['images'][$i]['id']) ?>"></a>
                        <?php endfor; ?>
                    </div>

                <?php endif; ?>
            </div>


            <div class="col-md-6 text">
                <h1>
                    <a href="/postdetail/<?php echo htmlspecialchars($v['id']) ?>"><?php echo htmlspecialchars($v['subject']) ?></a>
                </h1>

                <a href="/profile"><?php echo htmlspecialchars($v['login']) ?></a>

            </div>
            <div class="col-md-2 text-right">
                <h1><?php echo htmlspecialchars($v['price']) ?>$</h1>
            </div>
        </div>

    <?php endforeach; ?>
</div>

<script src="/application/assets/js/lightbox.min.js"></script>
