<div class="panel-wrap panel-primary center-block panel-wrap">
    <div class="panel-heading">
        <h3 class="panel-title">Registration: step 2</h3>
    </div>
    <div class="panel-body">
        <h3>Congratulations!</h3>

        <p>
            You are almost registered user. But you must confirm registration. We have sent you the email. Please, check
            your
            mailbox and finish registration.
        </p>
    </div>
</div>