<div class="panel-wrap panel-warning center-block panel-wrap" id="login">
    <div class="panel-heading">
        <h3 class="panel-title">Restore password to your account <span class="panel-text-right">Or <a href="/home">return
                    to home</a></span></h3>
    </div>
    <div class="panel-body">
        <p class="text-info">
            On your email will be sent letter with instructions how to restore access to your account.
        </p>

        <!-- Restore form start -->
        <form action="#" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" placeholder="Enter email">
            </div>

            <input type="submit" class="btn btn-warning pull-right" value="Restore">
        </form>
        <!-- Restore form start -->

    </div>
</div>