<div class="row">
    <div class="form-group search-only">
        <i class="search-icon glyphicon glyphicon-search"></i>
        <input type="text" autocomplete="off" id="page-search" class="form-control search-query"
               placeholder="Search">
    </div>
</div>

<div class="posts" id="posts">
    <h5 class="text-danger text-center"><?= $data['notFound'] ?></h5>
    <?php foreach ($data['searchResult'] as $v) : ?>
        <div class="row post-list vertical-align" id="post-list">
            <div class="col-md-2 text-right date-time">
                <h1><?= date("Y-m-d", $v['cDate']) ?></h1>

                <h2><?= date("H:m", $v['cDate']) ?></h2>
            </div>

            <div class="col-md-2 images">
                <a href="http://img.ads-board2/<?= $v['userId'] ?>/<?= $v['id'] ?>/<?= $v['img'] ?>"
                   data-lightbox="image-1" data-title="My caption">
                    <img src="http://img.ads-board2/<?= $v['userId'] ?>/<?= $v['id'] ?>/preview/thumb_<?= $v['img'] ?>"
                         alt="slider1" class="thumbnail img-responsive"/>
                </a>

            </div>

            <div class="col-md-6 text post-text">
                <h1>
                    <a href="/postdetail/<?= htmlspecialchars($v['id']) ?>"><?php echo htmlspecialchars($v['subject']) ?></a>
                </h1>

                <a href="/profile"><?= htmlspecialchars($v['login']) ?></a>

            </div>
            <div class="col-md-2 text-right post-price">
                <h1><?php echo htmlspecialchars($v['price']) ?>$</h1>
            </div>
        </div>
    <?php endforeach ?>
</div>
<script src="/application/assets/js/search.js"></script>
<script src="/application/assets/js/lightbox.min.js"></script>