<div class="row">
    <div class="col-md-12">
        <h3>Terms and Conditions</h3>
        <h4>
            In&nbsp;using this website you are deemed to&nbsp;have read and agreed to&nbsp;the following terms and
            conditions:
        </h4>

        <p>
            The following terminology applies to&nbsp;these Terms and Conditions, Privacy Statement and Disclaimer
            Notice and
            any
            or&nbsp;all Agreements: &laquo;Client&raquo;, &laquo;You&raquo; and &laquo;Your&raquo; refers to&nbsp;you,
            the
            person accessing this website and accepting the Company’s&nbsp;terms and conditions. &laquo;The
            Company&raquo;, &laquo;Ourselves&raquo;, &laquo;We&raquo; and &laquo;Us&raquo;, refers to&nbsp;our
            Company. &laquo;Party&raquo;, &laquo;Parties&raquo;,
            or&nbsp;&laquo;Us&raquo;, refers to&nbsp;both the Client and ourselves, or&nbsp;either the Client or&nbsp;ourselves.
            All terms refer to&nbsp;the offer, acceptance and consideration of&nbsp;payment necessary to&nbsp;undertake
            the
            process of&nbsp;our assistance to&nbsp;the Client in&nbsp;the most appropriate manner, whether by&nbsp;formal
            meetings of&nbsp;a&nbsp;fixed duration, or&nbsp;any other means, for the express purpose of&nbsp;meeting the
            Client’s&nbsp;needs in&nbsp;respect of&nbsp;provision of&nbsp;the Company’s&nbsp;stated services/products,
            in&nbsp;accordance
            with and subject to, prevailing English Law. Any use of&nbsp;the above terminology or&nbsp;other words in&nbsp;the
            singular, plural, capitalisation and/or he/she or&nbsp;they, are taken as&nbsp;interchangeable and therefore
            as&nbsp;referring
            to&nbsp;same.
        </p>
        <h4>Privacy Statement</h4>

        <p>
            We&nbsp;are committed to&nbsp;protecting your privacy. Authorized employees within the company on&nbsp;a&nbsp;need
            to&nbsp;know basis only use any information collected from individual customers. We&nbsp;constantly review
            our
            systems and data to&nbsp;ensure the best possible service to&nbsp;our customers. Parliament has created
            specific
            offences for unauthorised actions against computer systems and data. We&nbsp;will investigate any such
            actions with
            a&nbsp;view to&nbsp;prosecuting and/or taking civil proceedings to&nbsp;recover damages against those
            responsible
        </p>
        <h4>Confidentiality</h4>

        <p>
            We&nbsp;are registered under the Data Protection Act 1998 and as&nbsp;such, any information concerning the
            Client
            and their respective Client Records may be&nbsp;passed to&nbsp;third parties. However, Client records are
            regarded
            as&nbsp;confidential and therefore will not be&nbsp;divulged to&nbsp;any third party, other than our
            manufacturer/supplier(s) and if&nbsp;legally required to&nbsp;do&nbsp;so&nbsp;to&nbsp;the appropriate
            authorities.
            Clients have the right to&nbsp;request sight of, and copies of&nbsp;any and all Client Records we&nbsp;keep,
            on&nbsp;the
            proviso that we&nbsp;are given reasonable notice of&nbsp;such a&nbsp;request. Clients are requested to&nbsp;retain
            copies of&nbsp;any literature issued in&nbsp;relation to&nbsp;the provision of&nbsp;our services. Where
            appropriate,
            we&nbsp;shall issue Client’s&nbsp;with appropriate written information, handouts or&nbsp;copies of&nbsp;records
            as&nbsp;part
            of&nbsp;an&nbsp;agreed contract, for the benefit of&nbsp;both parties.
        </p>

        <p>
            We&nbsp;will not sell, share, or&nbsp;rent your personal information to&nbsp;any third party or&nbsp;use
            your e-mail
            address for unsolicited mail. Any emails sent by&nbsp;this Company will only be&nbsp;in&nbsp;connection with
            the
            provision of&nbsp;agreed services and products.
        </p>
        <h4>Exclusions and Limitations</h4>

        <p>
            The information on&nbsp;this web site is&nbsp;provided on&nbsp;an&nbsp;&laquo;as&nbsp;is&raquo; basis. To&nbsp;the
            fullest extent permitted by&nbsp;law, this Company:<br/>
            excludes all representations and warranties relating to&nbsp;this website and its contents or&nbsp;which is&nbsp;or&nbsp;may
            be&nbsp;provided by&nbsp;any affiliates or&nbsp;any other third party, including in&nbsp;relation to&nbsp;any
            inaccuracies or&nbsp;omissions in&nbsp;this website and/or the Company’s&nbsp;literature; and<br/>
            excludes all liability for damages arising out of&nbsp;or&nbsp;in&nbsp;connection with your use of&nbsp;this
            website. This includes, without limitation, direct loss, loss of&nbsp;business or&nbsp;profits (whether or&nbsp;not
            the loss of&nbsp;such profits was foreseeable, arose in&nbsp;the normal course of&nbsp;things or&nbsp;you
            have
            advised this Company of&nbsp;the possibility of&nbsp;such potential loss), damage caused to&nbsp;your
            computer,
            computer software, systems and programs and the data thereon or&nbsp;any other direct or&nbsp;indirect,
            consequential and incidental damages.<br/>
            This Company does not however exclude liability for death or&nbsp;personal injury caused by&nbsp;its
            negligence. The
            above exclusions and limitations apply only to&nbsp;the extent permitted by&nbsp;law. None of&nbsp;your
            statutory
            rights as&nbsp;a&nbsp;consumer are affected.
        </p>
        <h4>Payment</h4>

        <p>
            Cash or&nbsp;Personal Cheque with Bankers Card, all major Credit/Debit Cards, Bankers Draft or&nbsp;BACS
            Transfer
            are all acceptable methods of&nbsp;payment. Our Terms are payment in&nbsp;full within thirty days. All goods
            remain
            the property of&nbsp;the Company until paid for in&nbsp;full. Monies that remains outstanding by&nbsp;the
            due date
            will incur late payment interest at&nbsp;the rate of&nbsp;2% above the prevailing Bank of&nbsp;England&rsquo;s
            base
            rate on&nbsp;the outstanding balance until such time as&nbsp;the balance is&nbsp;paid in&nbsp;full and final
            settlement. We&nbsp;reserve the right to&nbsp;seek recovery of&nbsp;any monies remaining unpaid sixty days
            from the
            date of&nbsp;invoice via collection Agencies and/or through the Small Claims Court in&nbsp;the event that
            the
            outstanding balance does not exceed &#163;3000. In&nbsp;such circumstances, you shall be&nbsp;liable for any
            and all
            additional administrative and/or court costs. Amend as&nbsp;appropriate</p>

        <p>Returned cheques will incur a&nbsp;&#163;25 charge to&nbsp;cover banking fees and administrative costs. In&nbsp;an&nbsp;instance
            of&nbsp;a&nbsp;second Returned cheque, we&nbsp;reserve the right to&nbsp;terminate the arrangement and, if&nbsp;agreed
            to, we&nbsp;shall insist on&nbsp;future cash transactions only. Consequently, all bookings and/or
            transactions and
            agreements entered into will cease with immediate effect until such time as&nbsp;any and all outstanding
            monies are
            recovered in&nbsp;full.</p>
        <h4>Cancellation Policy</h4>

        <p>
            Minimum 24 hours notice of&nbsp;cancellation required. Notification for instance, in&nbsp;person, via email,
            mobile
            phone ‘text message’ and/or fax, or&nbsp;any other means will be&nbsp;accepted subject to&nbsp;confirmation
            in&nbsp;writing.
            We&nbsp;reserve the right to&nbsp;levy a&nbsp;&#163;30 charge to&nbsp;cover any subsequent administrative
            expenses.
        </p>
        <h4>Termination of&nbsp;Agreements and Refunds Policy</h4>

        <p>
            Both the Client and ourselves have the right to&nbsp;terminate any Services Agreement for any reason,
            including the
            ending of&nbsp;services that are already underway. No&nbsp;refunds shall be&nbsp;offered, where a&nbsp;Service
            is&nbsp;deemed
            to&nbsp;have begun and is, for all intents and purposes, underway. Any monies that have been paid to&nbsp;us&nbsp;which
            constitute payment in&nbsp;respect of&nbsp;the provision of&nbsp;unused Services, shall be&nbsp;refunded.
        </p>
        <h4>Availability</h4>

        <p>
            Unless otherwise stated, the services featured on&nbsp;this website are only available within the United
            Kingdom, or&nbsp;in&nbsp;relation
            to&nbsp;postings from the United Kingdom. All advertising is&nbsp;intended solely for the United Kingdom
            market. You
            are solely responsible for evaluating the fitness for a&nbsp;particular purpose of&nbsp;any downloads,
            programs and
            text available through this site. Redistribution or&nbsp;republication of&nbsp;any part of&nbsp;this site or&nbsp;its
            content is&nbsp;prohibited, including such by&nbsp;framing or&nbsp;other similar or&nbsp;any other means,
            without
            the express written consent of&nbsp;the Company. The Company does not warrant that the service from this
            site will
            be&nbsp;uninterrupted, timely or&nbsp;error free, although it&nbsp;is&nbsp;provided to&nbsp;the best
            ability. By&nbsp;using
            this service you thereby indemnify this Company, its employees, agents and affiliates against any loss or&nbsp;damage,
            in&nbsp;whatever manner, howsoever caused.
        </p>
        <h4>Log Files</h4>

        <p>
            We&nbsp;use IP&nbsp;addresses to&nbsp;analyse trends, administer the site, track user’s&nbsp;movement, and
            gather
            broad demographic information for aggregate use. IP&nbsp;addresses are not linked to&nbsp;personally
            identifiable
            information. Additionally, for systems administration, detecting usage patterns and troubleshooting
            purposes, our
            web servers automatically log standard access information including browser type, access times/open mail,
            URL
            requested, and referral URL. This information is&nbsp;not shared with third parties and is&nbsp;used only
            within
            this Company on&nbsp;a&nbsp;need-to-know basis. Any individually identifiable information related to&nbsp;this
            data
            will never be&nbsp;used in&nbsp;any way different to&nbsp;that stated above without your explicit
            permission.
        </p>
        <h4>Cookies</h4>

        <p>
            Like most interactive web sites this Company’s&nbsp;website [or&nbsp;ISP] uses cookies to&nbsp;enable us&nbsp;to&nbsp;retrieve
            user details for each visit. Cookies are used in&nbsp;some areas of&nbsp;our site to&nbsp;enable the
            functionality
            of&nbsp;this area and ease of&nbsp;use for those people visiting. Some of&nbsp;our affiliate partners may
            also use
            cookies. If&nbsp;you do&nbsp;not use cookies, delete this clause</p>
        <h4>Links to&nbsp;this website</h4>

        <p>
            You may not create a&nbsp;link to&nbsp;any page of&nbsp;this website without our prior written consent. If&nbsp;you
            do&nbsp;create a&nbsp;link to&nbsp;a&nbsp;page of&nbsp;this website you do&nbsp;so&nbsp;at&nbsp;your own
            risk and
            the exclusions and limitations set out above will apply to&nbsp;your use of&nbsp;this website by&nbsp;linking
            to&nbsp;it.
        </p>
        <h4>Links from this website</h4>

        <p>
            We&nbsp;do&nbsp;not monitor or&nbsp;review the content of&nbsp;other party’s&nbsp;websites which are linked
            to&nbsp;from
            this website. Opinions expressed or&nbsp;material appearing on&nbsp;such websites are not necessarily shared
            or&nbsp;endorsed
            by&nbsp;us&nbsp;and should not be&nbsp;regarded as&nbsp;the publisher of&nbsp;such opinions or&nbsp;material.
            Please
            be&nbsp;aware that we&nbsp;are not responsible for the privacy practices, or&nbsp;content, of&nbsp;these
            sites. We&nbsp;encourage
            our users to&nbsp;be&nbsp;aware when they leave our site & to&nbsp;read the privacy statements of&nbsp;these
            sites.
            You should evaluate the security and trustworthiness of&nbsp;any other site connected to&nbsp;this site or&nbsp;accessed
            through this site yourself, before disclosing any personal information to&nbsp;them. This Company will not
            accept
            any responsibility for any loss or&nbsp;damage in&nbsp;whatever manner, howsoever caused, resulting from
            your
            disclosure to&nbsp;third parties of&nbsp;personal information.</p>
        <h4>Copyright Notice</h4>

        <p>
            Copyright and other relevant intellectual property rights exists on&nbsp;all text relating to&nbsp;the
            Company’s&nbsp;services
            and the full content of&nbsp;this website.</p>

        <p>This Company’s&nbsp;logo is&nbsp;a&nbsp;registered trademark of&nbsp;this Company in&nbsp;the United Kingdom
            and
            other countries. The brand names and specific services of&nbsp;this Company featured on&nbsp;this web site
            are trade
            marked delete this paragraphed clause if&nbsp;no&nbsp;registered trademark exists.</p>
        <h4>Communication</h4>

        <p>
            We&nbsp;have several different e-mail addresses for different queries. These, & other contact information,
            can be&nbsp;found
            on&nbsp;our Contact Us&nbsp;link on&nbsp;our website or&nbsp;via Company literature or&nbsp;via the
            Company’s&nbsp;stated
            telephone, facsimile or&nbsp;mobile telephone numbers.
        </p>

        <p>
            This company is&nbsp;registered in&nbsp;England and Wales, Number 11111111, registered office 123 Any
            Street,
            Anytown
            AB2 3CD. Only need to&nbsp;state this if&nbsp;Limited Company, otherwise proprietors’/partners’ home/trading
            address
            must be&nbsp;shown, without use of&nbsp;the term: registered
        </p>
        <h4>Force Majeure</h4>

        <p>
            Neither party shall be&nbsp;liable to&nbsp;the other for any failure to&nbsp;perform any obligation under
            any
            Agreement which is&nbsp;due to&nbsp;an&nbsp;event beyond the control of&nbsp;such party including but not
            limited to&nbsp;any
            Act of&nbsp;God, terrorism, war, Political insurgence, insurrection, riot, civil unrest, act of&nbsp;civil
            or&nbsp;military
            authority, uprising, earthquake, flood or&nbsp;any other natural or&nbsp;man made eventuality outside of&nbsp;our
            control, which causes the termination of&nbsp;an&nbsp;agreement or&nbsp;contract entered into, nor which
            could have
            been reasonably foreseen. Any Party affected by&nbsp;such event shall forthwith inform the other Party of&nbsp;the
            same and shall use all reasonable endeavours to&nbsp;comply with the terms and conditions of&nbsp;any
            Agreement
            contained herein.
        </p>
        <h4>Waiver</h4>

        <p>
            Failure of&nbsp;either Party to&nbsp;insist upon strict performance of&nbsp;any provision of&nbsp;this or&nbsp;any
            Agreement or&nbsp;the failure of&nbsp;either Party to&nbsp;exercise any right or&nbsp;remedy to&nbsp;which
            it, he&nbsp;or&nbsp;they
            are entitled hereunder shall not constitute a&nbsp;waiver thereof and shall not cause a&nbsp;diminution of&nbsp;the
            obligations under this or&nbsp;any Agreement. No&nbsp;waiver of&nbsp;any of&nbsp;the provisions of&nbsp;this
            or&nbsp;any
            Agreement shall be&nbsp;effective unless it&nbsp;is&nbsp;expressly stated to&nbsp;be&nbsp;such and signed by&nbsp;both
            Parties.
        </p>
        <h4>General</h4>

        <p>
            The laws of&nbsp;England and Wales govern these terms and conditions. By&nbsp;accessing this website and
            using our
            services/buying our products you consent to&nbsp;these terms and conditions and to&nbsp;the exclusive
            jurisdiction
            of&nbsp;the English courts in&nbsp;all disputes arising out of&nbsp;such access. If&nbsp;any of&nbsp;these
            terms are
            deemed invalid or&nbsp;unenforceable for any reason (including, but not limited to&nbsp;the exclusions and
            limitations set out above), then the invalid or&nbsp;unenforceable provision will be&nbsp;severed from these
            terms
            and the remaining terms will continue to&nbsp;apply. Failure of&nbsp;the Company to&nbsp;enforce any of&nbsp;the
            provisions set out in&nbsp;these Terms and Conditions and any Agreement, or&nbsp;failure to&nbsp;exercise
            any option
            to&nbsp;terminate, shall not be&nbsp;construed as&nbsp;waiver of&nbsp;such provisions and shall not affect
            the
            validity of&nbsp;these Terms and Conditions or&nbsp;of&nbsp;any Agreement or&nbsp;any part thereof, or&nbsp;the
            right thereafter to&nbsp;enforce each and every provision. These Terms and Conditions shall not be&nbsp;amended,
            modified, varied or&nbsp;supplemented except in&nbsp;writing and signed by&nbsp;duly authorised
            representatives of&nbsp;the
            Company.
        </p>
        <h4>Notification of&nbsp;Changes</h4>

        <p>
            The Company reserves the right to&nbsp;change these conditions from time to&nbsp;time as&nbsp;it&nbsp;sees
            fit and
            your continued use of&nbsp;the site will signify your acceptance of&nbsp;any adjustment to&nbsp;these terms.
            If&nbsp;there
            are any changes to&nbsp;our privacy policy, we&nbsp;will announce that these changes have been made on&nbsp;our
            home
            page and on&nbsp;other key pages on&nbsp;our site. If&nbsp;there are any changes in&nbsp;how we&nbsp;use our
            site
            customers’ Personally Identifiable Information, notification by&nbsp; e-mail or&nbsp;postal mail will be&nbsp;made
            to&nbsp;those affected by&nbsp;this change. Any changes to&nbsp;our privacy policy will be&nbsp;posted on&nbsp;our
            web site 30 days prior to&nbsp;these changes taking place. You are therefore advised to&nbsp;re-read this
            statement
            on&nbsp;a&nbsp;regular basis
        </p>

        <p>These terms and conditions form part of&nbsp;the Agreement between the Client and ourselves. Your accessing
            of&nbsp;this
            website and/or undertaking of&nbsp;a&nbsp;booking or&nbsp;Agreement indicates your understanding, agreement
            to&nbsp;and
            acceptance, of&nbsp;the Disclaimer Notice and the full Terms and Conditions contained herein. Your statutory
            Consumer Rights are unaffected.
        </p>

        <h5>
            Copyright &copy; 2015 Ads board. All Rights Reserved
        </h5>
        <br/>
        <br/>
        <br/>
    </div>
</div>