<div ng-controller="userCtrl" class="row admin-user">

    <h3>Users management</h3>

    <table st-table="displayedCollection" st-safe-src="rowCollection" class="table table-striped">
        <thead>
        <tr>
            <th st-sort="id" class="col-md-1">Id</th>
            <th st-sort="login" class="col-md-4">Login</th>
            <th st-sort="email" class="col-md-4">Email</th>
            <th st-sort="status" class="col-md-1">Status</th>
            <th st-sort="role" class="col-md-1">Role</th>
            <!--            <th st-sort="name">Name</th>-->

            <th class="col-md-1">Banned</th>
        </tr>
        <tr>
            <th colspan="6"><input st-search="" class="form-control" placeholder="Search ..." type="text"/></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="row in displayedCollection">
            <td>{{row.id}}</td>
            <td>{{row.login}}</td>
            <td>{{row.email}}</td>
            <td>{{row.status}}</td>
            <td>{{row.role}}</td>
            <td>
                <button ng-click="ban(row)" class="btn btn-danger">Ban</button>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script src="/application/assets/js/adminUsers.js"></script>