<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'/>

    <title>Ads-board2</title>

    <link href="/application/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/application/assets/css/bootflat.css" rel="stylesheet">
    <link href="/application/assets/css/style.css" rel="stylesheet">
    <link href="/application/assets/css/component.css" rel="stylesheet">
    <link href="/application/assets/css/lightbox.css" rel="stylesheet"/>
    <link href="/application/assets/css/dropzone.css" rel="stylesheet"/>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.15/slick.css"/>

    <link
        href='http://fonts.googleapis.com/css?family=Exo+2:400,300,300italic,400italic,700,700italic&subset=latin,cyrillic'
        rel='stylesheet' type='text/css'>

    <script src="/application/assets/js/jquery-1.10.1.min.js"></script>
    <script src="/application/assets/js/bootstrap.min.js"></script>
    <script src="/application/assets/js/goToTop.js"></script>

</head>

<body>

<header>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home">ADS BOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                            aria-expanded="false">Admin <!--<?= $_SESSION['userLogin']; ?>--><span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/logout"><i class="icon-sign-out"></i> Logout</a></li>
                        </ul>
                    </li>
                    <?php ; ?>

                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container" id="home">
    <div class="row">
        <div class="col-md-2">
            <aside>
                <div class="list-group">
                    <a href="/admin/users" class="list-group-item">Users</a>
                    <a href="/admin/plans" class="list-group-item">Plans</a>
                    <a href="/admin/categories" class="list-group-item">Categories</a>
                    <a href="/admin/advertisements" class="list-group-item">Advertisements</a>
                </div>
            </aside>
        </div>
        <div class="col-md-10">
            <?php echo $content ?>
        </div>

    </div>
</main>


<footer>
    <div class="container">
        <p class="pull-left">Copyright&nbsp;&copy;&nbsp;
            <script type="text/javascript">
                document.write(new Date().getFullYear());
            </script>
            Ads Board. All rights reserved.
        </p>

        <p class="pull-right">
            <a href="/home">Home</a>&emsp;
            <a href="/about">About</a>&emsp;
            <a href="/home/pricing">Pricing</a>&emsp;
            <a href="/terms">Terms</a>&emsp;
            <a href="#" data-toggle="modal" data-target="#contactUs">Contact us</a>
        </p>
    </div>
</footer>
<div id="top-link">
    <a href="#top"><span id="topicon"></span></a>
</div>
</body>
</html>