<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Page not found!</title>

    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'/>

    <link href="/application/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/application/assets/css/bootflat.css" rel="stylesheet">
    <link href="/application/assets/css/style.css" rel="stylesheet">
    <link
        href='http://fonts.googleapis.com/css?family=Exo+2:400,300,300italic,400italic,700,700italic&subset=latin,cyrillic'
        rel='stylesheet' type='text/css'>

</head>
<body>
<div class="container">
    <div class="center-block img-responsive">
        <?php echo $content ?>
        <div class="text-center error-text">
            <a href="/home">Go to home and try again.</a>
        </div>
    </div>
</div>

</body>
</html>