<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project</title>

    <!-- Bootstrap core CSS -->
    <link href="/application/assets/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/home">Home</a>
            <a class="navbar-brand" href="/registration">Registration</a>
            <?php
            if ($_SESSION['userRole'] == 'guest') {
                echo '<a class="navbar-brand" href="/login">Login</a>';
            } else {
                echo '<a class="navbar-brand" href="/logout">Logout</a>';
            }
            ?>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <!--            <form class="navbar-form navbar-right" role="form">-->
            <!--                <div class="form-group">-->
            <!--                    <input type="text" placeholder="Email" class="form-control">-->
            <!--                </div>-->
            <!--                <div class="form-group">-->
            <!--                    <input type="password" placeholder="Password" class="form-control">-->
            <!--                </div>-->
            <!--                <button type="submit" class="btn btn-success">Sign in</button>-->
            <!--            </form>-->
        </div>
        <!--/.navbar-collapse -->
    </div>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>

        <p>This is a template for a simple marketing or informational website. It includes a large callout called a
            jumbotron and three supporting pieces of content. Use it as a starting point to create something more
            unique.</p>

        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <?php echo $content ?>


</div>
<!-- /container -->
<hr>

<footer class="container">
    <p>&copy; Company 2014</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="/application/assets/js/bootstrap.min.js"></script>
</body>
</html>
