<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'/>

    <title>Ads-board2</title>

    <link href="/application/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/application/assets/css/bootflat.css" rel="stylesheet">
    <link href="/application/assets/css/style.css" rel="stylesheet">
    <link href="/application/assets/css/component.css" rel="stylesheet">
    <link href="/application/assets/css/lightbox.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.15/slick.css"/>

    <link
        href='http://fonts.googleapis.com/css?family=Exo+2:400,300,300italic,400italic,700,700italic&subset=latin,cyrillic'
        rel='stylesheet' type='text/css'>


    <script src="/application/assets/js/jquery-1.10.1.min.js"></script>
    <script src="/application/assets/js/bootstrap.min.js"></script>


</head>

<body>

<header>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home">ADS BOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-navbar-collapse">

                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group search-only">
                        <i class="search-icon glyphicon glyphicon-search"></i>
                        <input type="text" class="form-control search-query" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-info" data-type="last">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/home/postlist"><i class="glyphicon glyphicon-eye-open"></i> Watch ads</a></li>
                    <?php
                    if ($_SESSION['userRole'] == 'guest') {
                        echo '<li class="btn btn-xs btn-primary"><a href="/registration" ><i class="icon-user-add"></i> Sing up</a></li>
                              <li class="btn btn-xs btn-success"><a href="/login"><i class="icon-sign-in"></i> Sing in</a></li>';
                    } else {
                        echo '<li><a href=""><i class="glyphicon glyphicon-plus-sign"></i> Create new ads <span class="badge">1</span></a></li>
                              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">[Username] <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                <li><a href="#"><i class="icon-widget"></i> Profile</a></li>
                                <li class="divider"></li><li><a href="/user/logout"><i class="icon-sign-out"></i> Logout</a></li>
                              </ul></li>';
                    }
                    ?>

                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container" id="home">

    <?php echo $content ?>

</main>

<footer>
    <div class="container">
        <p class="pull-left">&copy;&nbsp;Copyright&nbsp;</p>

        <p class="pull-right"><a href="/home">Home</a>&emsp;<a href="#">About</a>&emsp;<a
                href="/home/pricing">Pricing</a>&emsp;<a href="#">Terms</a>&emsp;<span
                id="09;"></span><a href="#">Contact
                us</a></p>
    </div>
</footer>

</body>
</html>